repos:
  - repo: local
    hooks:
    - id: black
      name: black
      entry: black
      language: python
      types: [python]
      exclude: ^spikes
    - id: flake8
      name: flake8
      entry: flake8
      language: python
      types: [python]
      exclude: ^spikes
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.5.0
    hooks:
    - id: check-added-large-files
    - id: end-of-file-fixer
    - id: mixed-line-ending
    - id: no-commit-to-branch
    - id: pretty-format-json
      args: [--no-sort-keys]
